---
- name: 'Enable systemd services and timers'
  become: true
  block:
      - name: 'Start smartcard socket (pcscd.socket)'
        ansible.builtin.systemd:
            name: 'pcscd.socket'
            enabled: true
            daemon_reload: true
        tags:
            - 'always'
            - 'systemd'
            - 'yubikey'

      - name: 'Start smartcard service (pcscd.service)'
        ansible.builtin.systemd:
            name: 'pcscd.service'
            enabled: true
            daemon_reload: true
        tags:
            - 'always'
            - 'systemd'
            - 'yubikey'

      - name: 'Discard trim enable'
        ansible.builtin.systemd:
            name: 'fstrim.timer'
            state: 'started'
            enabled: true
            daemon_reload: true
        tags:
            - 'always'
            - 'systemd'
...
